version: "3"
services: 
  web:
    build: .
    ports: 
      - "8080:4000"
    volumes: 
      - .:/home/node/code/
      - /home/node/code/node_modules
    links: 
      - db
    environment: 
      MONGO_URL: mongodb://db:27017
  db:
    image: mongo:3